### ISSUE TITLE
Rename repository to avoid confusion with renovatebot/github-actions

### ISSUE THREAD

**Issue by rarkins** [renovatebot/internal-tools#24]
We also need to update any repos referencing it.

**Comment by viceice** [comment]
Ok, what name do you prefer?

**Comment by rarkins** [comment]
Something like `internal-tools` or `internal-actions`?

**Comment by viceice** [comment]
So please rename to `internal-tools`, I'll open pr's to switch to new name.

I think (hope) github will follow repo rename like normal git poperations
