### ISSUE TITLE
feat(docker-builder): speedup major-minor tags

### ISSUE THREAD

**Issue by viceice** [renovatebot/internal-tools#44]
Currently every patch release is taged as latest major and major.minor and possible overwriten by next patch release, wich will be build right after current version.

*Tasks*
* Find highest release for every major and major.minor
* tag and push major and major.minor only for latest matching release

**Comment by rarkins** [comment]
Can we do the major and major.minor tagging very last, instead of evaluating it each image that's built?

**Comment by viceice** [comment]
sounds good
