### ISSUE TITLE
Wrong value for org.opencontainers.image.version label

### ISSUE THREAD

**Issue by crazy-max** [renovatebot/internal-tools#53]
Hi,

The value of Docker label `org.opencontainers.image.version` should be `19.221.0` instead of `19.221.0-slim` for `renovate/renovate:19.221.0` (ref https://github.com/renovatebot/docker-renovate/issues/15#issuecomment-620746043).

**Comment by viceice** [comment]
The version arg should not contain the docker tag suffix

**Comment by crazy-max** [comment]
@viceice Yep that's it. `ARG` are not propagated after a `FROM`. Just add `ARG RENOVATE_VERSION` after your `FROM` and it will be fine:

```
# renovate: datasource=npm depName=renovate versioning=npm
ARG RENOVATE_VERSION=19.221.0

FROM renovate/renovate:$RENOVATE_VERSION-slim

ARG RENOVATE_VERSION
```

**Comment by viceice** [comment]
@crazy-max With next image rebuilds the version should be right

**Comment by crazy-max** [comment]
@viceice 

Not fixed for me:

```
$ docker pull renovate/renovate:19
$ docker inspect --format '{{ index .Config.Labels "org.opencontainers.image.version"}}' renovate/renovate:19
19.221.0-slim
```
